# Generated by Django 6.0.3 on 2026-03-25 20:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('tech', 'Technical'), ('nontech', 'Non-Technical')], default='nontech', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('malware', 'Malware'), ('data_loss', 'Data Loss'), ('denial_of_service', 'DoS')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('status', models.CharField(choices=[('in progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in progress', max_length=20)),
                ('scenario_json', models.JSONField()),
                ('score', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('pressure_level', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebriefSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debrief_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debrief', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'unique_together': {('slug', 'difficulty', 'version')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=120, unique=True)),
                ('stage_name', models.CharField(choices=[('prepare', 'Prepare'), ('detect', 'Detect'), ('analyse', 'Analyse'), ('remediate', 'Remediation'), ('post_incident', 'Post-Incident')], max_length=20)),
                ('prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook', to='gameplay.playbook')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('question_uid', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('options_json', models.JSONField()),
                ('selected_option_id', models.CharField(max_length=10)),
                ('time_limit_seconds', models.IntegerField(default=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer_is_correct', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_id', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gameplay.questionrun')),
            ],
        ),
        migrations.CreateModel(
            name='StageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('prepare', 'Prepare'), ('detect', 'Detect'), ('analyse', 'Analyse'), ('remediate', 'Remediation'), ('post_incident', 'Post-Incident')], max_length=50)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('done', 'Done')], default='locked', max_length=10)),
                ('order_index', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_uid', models.CharField(max_length=1)),
                ('option_text', models.TextField()),
                ('outcome', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='gameplay.generatedquestion')),
            ],
            options={
                'unique_together': {('question', 'option_uid')},
            },
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['playbook', 'stage_name'], name='gameplay_ge_playboo_9187a7_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['id'], name='gameplay_ge_id_dbdcbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionrun',
            constraint=models.UniqueConstraint(fields=('session', 'question_uid'), name='unique_question_uid_per_session'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question',), name='one_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='stagerun',
            constraint=models.UniqueConstraint(fields=('session', 'stage_name'), name='unique_stage_name_per_session'),
        ),
    ]
